import {
  ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  PieChart, Pie, Cell, AreaChart, Area, Legend,
} from "recharts";
import { useState } from "react";
import {
  FiUsers, FiUserCheck, FiPieChart, FiTrendingUp, FiArrowUp, FiArrowDown,
  FiClock, FiSmile, FiZap, FiAlertTriangle, FiCpu,
} from "react-icons/fi";
import { Card } from "../ui/card";
import { Button } from "../ui/button";
import { useAuth } from "../../store/auth";
import { api } from "../../api";
import { emotionColor, GENDER_COLORS, axisProps } from "./theme";
import { pctDelta, positivityIndex, hourTotals, buildInsights, detectAnomalies } from "../../lib/format";

const AiSummaryCard = ({ summary }) => {
  const { isOffline } = useAuth();
  const [loading, setLoading] = useState(false);
  const [text, setText] = useState("");
  const [err, setErr] = useState("");

  const generate = async () => {
    setLoading(true); setErr("");
    try {
      const res = await api.post("/api/ai/insights", { summary });
      setText(res.data.insight);
    } catch (e) {
      setErr(e.response?.data?.message || "Couldn't generate a summary.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="p-6">
      <div>
        <h3 className="flex items-center gap-2 text-base font-semibold"><FiCpu className="text-primary" /> AI summary</h3>
        <p className="mt-1 text-sm text-muted-foreground">A written read of this view, generated by your chosen model.</p>
      </div>
      <Button size="sm" className="mt-3 w-full" onClick={generate} disabled={loading || isOffline}>
        {loading ? "Generating…" : "Generate"}
      </Button>
      <div className="mt-4 text-sm leading-relaxed">
        {isOffline ? (
          <p className="text-muted-foreground">Connect to the server to generate AI summaries.</p>
        ) : err ? (
          <p className="text-muted-foreground">{err}</p>
        ) : text ? (
          <p className="whitespace-pre-wrap text-foreground/90">{text}</p>
        ) : (
          <p className="text-muted-foreground">Click <span className="font-medium">Generate</span> for a natural-language summary (Groq by default, or your own provider).</p>
        )}
      </div>
    </Card>
  );
};

const num = (n) => (n ?? 0).toLocaleString();

const CustomTooltip = ({ active, payload, label }) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="rounded-xl border border-border bg-card/95 px-3 py-2 text-xs shadow-lift backdrop-blur">
      {label != null && <div className="mb-1 font-medium text-foreground">{label}</div>}
      {payload.map((p) => (
        <div key={p.name} className="flex items-center gap-2 text-muted-foreground">
          <span className="h-2 w-2 rounded-full" style={{ background: p.color || p.payload?.fill }} />
          <span className="capitalize">{p.name}</span>
          <span className="ml-auto font-mono text-foreground">{num(p.value)}</span>
        </div>
      ))}
    </div>
  );
};

const Delta = ({ value, unit = "%" }) => {
  if (value == null) return null;
  const up = value >= 0;
  return (
    <span className={`inline-flex items-center gap-0.5 rounded-full px-1.5 py-0.5 text-xs font-medium ${up ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : "bg-red-500/10 text-red-600 dark:text-red-400"}`}>
      {up ? <FiArrowUp size={11} /> : <FiArrowDown size={11} />}{Math.abs(value)}{unit}
    </span>
  );
};

const StatCard = ({ icon: Icon, label, value, sub, delta }) => (
  <Card className="p-5">
    <div className="flex items-center justify-between">
      <span className="text-xs font-medium uppercase tracking-widest text-muted-foreground">{label}</span>
      <span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary"><Icon size={16} /></span>
    </div>
    <div className="mt-4 flex items-center gap-2">
      <span className="font-mono text-3xl font-semibold tracking-tight">{value}</span>
      {delta != null && <Delta value={delta} />}
    </div>
    {sub && <div className="mt-1 text-sm text-muted-foreground">{sub}</div>}
  </Card>
);

const HighlightTile = ({ icon: Icon, label, value, delta }) => (
  <Card className="flex items-center gap-4 p-5">
    <span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-secondary text-foreground"><Icon size={18} /></span>
    <div>
      <div className="text-xs uppercase tracking-widest text-muted-foreground">{label}</div>
      <div className="mt-0.5 flex items-center gap-2">
        <span className="font-mono text-xl font-semibold">{value}</span>
        {delta != null && <Delta value={delta} unit=" pts" />}
      </div>
    </div>
  </Card>
);

const ChartCard = ({ title, description, children, className = "" }) => (
  <Card className={`p-6 ${className}`}>
    <h3 className="text-base font-semibold">{title}</h3>
    {description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}
    <div className="mt-5">{children}</div>
  </Card>
);

export const DashboardView = ({ summary, prevSummary, recent = [] }) => {
  const { total = 0, gender = {}, genderAge = [], emotion = {}, gi = {}, byHour = [], ageEmotionMatrix = [] } = summary;

  const female = gender.Female || 0, male = gender.Male || 0;
  const femalePct = total ? Math.round((female / total) * 100) : 0;
  const malePct = total ? Math.round((male / total) * 100) : 0;
  const topAge = (summary.age || []).reduce((a, b) => (b.count > (a?.count || 0) ? b : a), null);

  // Comparison + highlights.
  const totalDelta = prevSummary ? pctDelta(total, prevSummary.total) : null;
  const pos = positivityIndex(emotion);
  const posDelta = prevSummary ? pos - positivityIndex(prevSummary.emotion) : null;
  const hours = hourTotals(byHour);
  const busiest = hours.reduce((a, b) => (b.total > (a?.total || 0) ? b : a), null);
  const happiest = hours.reduce((a, b) => (b.happy > (a?.happy || 0) ? b : a), null);
  const insights = buildInsights(summary, prevSummary);
  const anomalies = detectAnomalies(byHour);

  const emotionData = Object.entries(emotion).map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value);
  const giData = [
    { name: "Individuals", value: gi.individual || 0 },
    { name: "Groups", value: gi.group || 0 },
  ];
  const hourEmotions = Array.from(new Set(byHour.flatMap((h) => Object.keys(h).filter((k) => k !== "hour"))));

  const ages = Array.from(new Set(ageEmotionMatrix.map((d) => d.age)));
  const emotionsInMatrix = ["Happy", "Neutral", "Surprise", "Sad", "Fear", "Angry", "Disgust"];
  const matrixLookup = {};
  let matrixMax = 0;
  for (const d of ageEmotionMatrix) {
    matrixLookup[`${d.age}|${d.emotion}`] = d.count;
    if (d.count > matrixMax) matrixMax = d.count;
  }

  return (
    <div className="grid gap-6 xl:grid-cols-[300px_minmax(0,1fr)_280px]">
      {/* Left: AI summary (sticky on scroll) */}
      <aside className="order-2 xl:order-1 xl:sticky xl:top-20 xl:self-start">
        <AiSummaryCard summary={summary} />
      </aside>

      {/* Center column */}
      <div className="order-1 min-w-0 space-y-6 xl:order-2">
      {/* KPIs */}
      <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 2xl:grid-cols-4">
        <StatCard icon={FiUsers} label="Total visitors" value={num(total)} sub="readings in range" delta={totalDelta} />
        <StatCard icon={FiUserCheck} label="Individuals : Groups" value={`${num(gi.individual || 0)}:${num(gi.group || 0)}`} sub="solo vs. accompanied" />
        <StatCard icon={FiPieChart} label="Gender split" value={`${femalePct}% F`} sub={`${malePct}% male`} />
        <StatCard icon={FiTrendingUp} label="Top age group" value={topAge?.age || "—"} sub={topAge ? `${num(topAge.count)} visitors` : "no data"} />
      </div>

      {/* Anomalies (only when detected) */}
      {anomalies.length > 0 && (
        <Card className="border-amber-500/30 bg-amber-500/[0.06] p-5">
          <h3 className="flex items-center gap-2 text-sm font-semibold text-amber-700 dark:text-amber-400">
            <FiAlertTriangle size={16} /> Anomalies detected
          </h3>
          <ul className="mt-2 space-y-1.5">
            {anomalies.map((a, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-foreground/90">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500" />{a}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Insights + recent feed */}
      <div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]">
        <ChartCard title="Today's takeaways" description="Auto-generated highlights from the current view.">
          <ul className="space-y-3">
            {insights.length ? insights.map((t, i) => (
              <li key={i} className="flex items-start gap-3 text-sm">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span className="text-foreground/90">{t}</span>
              </li>
            )) : <li className="text-sm text-muted-foreground">Not enough data for insights yet.</li>}
          </ul>
        </ChartCard>

        <ChartCard title="Recent visitors" description="Latest readings as they arrive.">
          <ul className="-mx-2 max-h-[260px] space-y-1 overflow-y-auto">
            {recent.length ? recent.map((r) => (
              <li key={r._id} className="flex items-center gap-3 rounded-lg px-2 py-2 hover:bg-secondary/60">
                <span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: emotionColor(r.Emotion) }} />
                <span className="font-mono text-xs text-muted-foreground">{(r.Time || "").slice(0, 5)}</span>
                <span className="text-sm">{r.Gender}, {r.Age}</span>
                <span className="ml-auto text-xs text-muted-foreground">{r.Emotion}</span>
                {r.Gi === "group" && <span className="rounded-full bg-secondary px-1.5 py-0.5 text-[10px] text-muted-foreground">group</span>}
              </li>
            )) : <li className="px-2 py-2 text-sm text-muted-foreground">No recent readings.</li>}
          </ul>
        </ChartCard>
      </div>

      {/* Row: gender by age + emotion donut */}
      <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
        <ChartCard title="Visitors by age & gender" description="Distribution of visitors across age groups, split by gender.">
          <ResponsiveContainer width="100%" height={320}>
            <BarChart data={genderAge} margin={{ top: 8, right: 8, left: -16, bottom: 0 }} barGap={4}>
              <CartesianGrid vertical={false} stroke="hsl(var(--border))" strokeDasharray="3 3" />
              <XAxis dataKey="age" {...axisProps} />
              <YAxis {...axisProps} />
              <Tooltip content={<CustomTooltip />} cursor={{ fill: "hsl(var(--muted))", opacity: 0.5 }} />
              <Bar dataKey="Female" fill={GENDER_COLORS.Female} radius={[4, 4, 0, 0]} maxBarSize={28} />
              <Bar dataKey="Male" fill={GENDER_COLORS.Male} radius={[4, 4, 0, 0]} maxBarSize={28} />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Emotion mix" description="Share of each detected emotion.">
          <ResponsiveContainer width="100%" height={320}>
            <PieChart>
              <Pie data={emotionData} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={62} outerRadius={100} paddingAngle={2} stroke="none">
                {emotionData.map((e) => <Cell key={e.name} fill={emotionColor(e.name)} />)}
              </Pie>
              <Tooltip content={<CustomTooltip />} />
              <Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      {/* Row: emotions over time + groups donut */}
      <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
        <ChartCard title="Emotions over time" description="How mood shifts across the hours of the day.">
          <ResponsiveContainer width="100%" height={300}>
            <AreaChart data={byHour} margin={{ top: 8, right: 8, left: -16, bottom: 0 }}>
              <defs>
                {hourEmotions.map((e) => (
                  <linearGradient key={e} id={`grad-${e}`} x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor={emotionColor(e)} stopOpacity={0.35} />
                    <stop offset="100%" stopColor={emotionColor(e)} stopOpacity={0} />
                  </linearGradient>
                ))}
              </defs>
              <CartesianGrid vertical={false} stroke="hsl(var(--border))" strokeDasharray="3 3" />
              <XAxis dataKey="hour" {...axisProps} tickFormatter={(h) => `${h}:00`} />
              <YAxis {...axisProps} />
              <Tooltip content={<CustomTooltip />} />
              <Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} />
              {hourEmotions.map((e) => (
                <Area key={e} type="monotone" dataKey={e} stroke={emotionColor(e)} strokeWidth={2} fill={`url(#grad-${e})`} />
              ))}
            </AreaChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Individuals vs. groups" description="Are visitors arriving solo or together?">
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie data={giData} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={62} outerRadius={100} paddingAngle={2} stroke="none">
                <Cell fill="hsl(var(--primary))" />
                <Cell fill="hsl(var(--chart-2))" />
              </Pie>
              <Tooltip content={<CustomTooltip />} />
              <Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      {/* Age x Emotion heatmap */}
      <ChartCard title="Age × emotion" description="Where emotion concentrates across age groups — darker means more.">
        <div className="overflow-x-auto">
          <div className="min-w-[560px] max-w-[760px]">
            <div className="grid" style={{ gridTemplateColumns: `90px repeat(${emotionsInMatrix.length}, 1fr)` }}>
              <div />
              {emotionsInMatrix.map((e) => (
                <div key={e} className="px-1 pb-2 text-center text-xs font-medium text-muted-foreground">{e}</div>
              ))}
              {ages.map((age) => (
                <Row key={age} age={age} emotions={emotionsInMatrix} lookup={matrixLookup} max={matrixMax} />
              ))}
            </div>
          </div>
        </div>
      </ChartCard>
      </div>

      {/* Right: highlight tiles (sticky on scroll) */}
      <aside className="order-3 grid gap-4 sm:grid-cols-3 xl:grid-cols-1 xl:sticky xl:top-20 xl:self-start">
        <HighlightTile icon={FiClock} label="Peak hour" value={busiest ? `${busiest.hour}:00` : "—"} />
        <HighlightTile icon={FiSmile} label="Happiest hour" value={happiest && happiest.happy ? `${happiest.hour}:00` : "—"} />
        <HighlightTile icon={FiZap} label="Mood index" value={`${pos}%`} delta={posDelta} />
      </aside>
    </div>
  );
};

const Row = ({ age, emotions, lookup, max }) => (
  <>
    <div className="flex items-center pr-3 font-mono text-xs text-muted-foreground">{age}</div>
    {emotions.map((e) => {
      const v = lookup[`${age}|${e}`] || 0;
      const intensity = max ? v / max : 0;
      return (
        <div key={e} className="p-1">
          <div
            className="grid aspect-square place-items-center rounded-md text-xs font-medium transition-colors"
            style={{
              background: `hsl(var(--primary) / ${0.08 + intensity * 0.85})`,
              color: intensity > 0.55 ? "hsl(var(--primary-foreground))" : "hsl(var(--muted-foreground))",
            }}
            title={`${age} · ${e}: ${v}`}
          >
            {v || ""}
          </div>
        </div>
      );
    })}
  </>
);
